### ISSUE TITLE
[FEAT] 지도에 현 위치 기능 추가

### ISSUE THREAD

**Issue by woog2roid** [kuku-train/kukutrain#2]
### 현재 상황
- 단순히 지도에 식당의 위치를 표현하였을 뿐, 현 위치를 알 수 없음

### 기능 추가
- 현 위치 버튼을 추가하여, 조금 더 잘 구현된 지도의 모습을 가질 수 있도록 할 것
  - 사용자가 맵을 따로 조작하지 않으면, 매 2초마다 현 위치를 확인하여 중앙 정렬할 수 있도록
  - 사용자가 맵을 한번이라도 조작했다면, 위 기능은 비활성화 할 것
  - 즉, 카카오맵을 거의 그대로 가져올 수 있도록 하는 것이 목표

### 참고
- /src/components/MapContainer를 확인해보면, 카카오맵으로 작성된 것을 알 수 있음
- 현 위치를 받기 위해, 카카오의 latlng을 사용할 수도 있으며, Geolocation API을 사용할 수 있음

**Comment by JaerryLee** [comment]
navigator.geolocation 라이브러리로 브라우저에서 사용자 위치를 받고, kakao.maps.LatLng으로 처리 ?

**Comment by woog2roid** [comment]
https://apis.map.kakao.com/web/sample/addr2coord/

이렇게 할 수 있지 않을까 생각해 봤습니다.
위의 링크에 코드 있어요.

**Comment by JaerryLee** [comment]
현위치 버튼 + 정렬 로직 먼저 구현할게용

**Comment by woog2roid** [comment]
넹~ 그러면 유림님께서 PWA 쪽 담당해주시는 건가요?

**Comment by JaerryLee** [comment]
업무 나누는건 아직 안정했습니다 😥
